import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function PostsLayout({ children }) {
  return (
    <div>
      <h2>You're on the Posts Page</h2>
      <h3>Post Actions</h3>
      <Link href="/posts">All Posts</Link>
      <Link href="/posts/addpost">Add New Post</Link>

      {children}
    </div>
  );
}
